admin_index:
    path:     /
    defaults: { _controller: DutafBundle:Admin:index }

admin_article_view:
    path: /articles
    defaults:
        _controller: DutafBundle:Admin:viewArticle

admin_article_add:
    path: /article/add
    defaults:
        _controller: DutafBundle:Article:add

admin_article_delete:
    path: /article/delete/{id}
    defaults:
        _controller: DutafBundle:Article:delete
    requirements:
        id: \d+

admin_article_edit:
    path: /article/edit/{id}
    defaults:
        _controller: DutafBundle:Article:edit
    requirements:
        id: \d+

admin_fournisseur_view:
    path: /fournisseurs
    defaults:
        _controller: DutafBundle:Admin:viewFournisseur

admin_fournisseur_add:
    path: /fournisseur/add
    defaults:
        _controller: DutafBundle:Fournisseur:add

admin_fournisseur_delete:
    path: /fournisseur/delete/{id}
    defaults:
        _controller: DutafBundle:Fournisseur:delete
    requirements:
        id: \d+

admin_fournisseur_edit:
    path: /fournisseur/edit/{id}
    defaults:
        _controller: DutafBundle:Fournisseur:edit
    requirements:
        id: \d+