dutaf_index:
    path:     /
    defaults: { _controller: DutafBundle:Article:index }

dutaf_article_view:
    path: /catalogue
    defaults:
        _controller: DutafBundle:Article:view

dutaf_article_budget:
    path: /catalogue/budget/{prix}
    defaults:
        _controller: DutafBundle:Article:budget
    requirements:
        prix: \d+

login:
    path: /login
    defaults:
        _controller: DutafBundle:Security:login

logout:
    path: /logout