dutaf_index:
    path:     /
    defaults: { _controller: DutafBundle:Article:index }

dutaf_article_view:
    path: /catalogue
    defaults:
        _controller: DutafBundle:Article:view

login:
    path: /login
    defaults:
        _controller: DutafBundle:Security:login

logout:
    path: /logout