dutaf_index:
    path:     /
    defaults: { _controller: DutafBundle:Article:index }

dutaf_article_view:
    path: /catalogue
    defaults:
        _controller: DutafBundle:Article:view

dutaf_article_add:
    path: /add
    defaults:
        _controller: DutafBundle:Article:add

dutaf_article_delete:
    path: /delete/{id}
    defaults:
        _controller: DutafBundle:Article:delete
    requirements:
        id: \d+

dutaf_article_edit:
    path: /edit/{id}
    defaults:
        _controller: DutafBundle:Article:edit
    requirements:
        id: \d+

dutaf_fournisseur_view:
    path: /fournisseurs
    defaults:
        _controller: DutafBundle:Fournisseur:view